- hosts: all
  become: true
  become_user: root
  tasks:

##### SERVICOS #####
  - name: "Verifica Firewall UP/DOWN"
    service: name=firewalld state=stopped
  - name: "Desabilita Firewall"
    service: name=firewalld enabled=no
  - name: "Desabilita SELinux"
    selinux:
      state: disabled
  - name: "instalar java"
    yum: name=java state=latest

##### COPIAR PACOTES #####
  - name: "Copia pacote do Java para o diretorio de instalação"
    copy:
     src: "/etc/ansible/arquivos/jboss_liferay/jdk1.7.0_151.zip"
     dest: "/opt/jdk1.7.0_151.zip"
  - name: "Copia arquivos de Instalacao para /opt"
    copy:
     src: "/etc/ansible/arquivos/jboss_liferay/liferay.zip"
     dest: "/opt/liferay.zip"
  - name: "Descompactar Bumdle Liferay"
    shell: "cd /opt/; unzip liferay.zip"
  - name: "Configura standalone"
    copy:
     src: "/etc/ansible/arquivos/jboss_liferay/standalone.xml"
     dest: "/opt/liferay/jboss-eap-6.4/standalone/configuration/standalone.xml"

##### CONFIGURACOES #####
  - name: "Descompactar Java"
    shell: "cd /opt/; unzip jdk1.7.0_151.zip"
  - name: "Cria link simbolico"
    file:
     src: /opt/jdk1.7.0_151
     dest: /opt/java
     state: link
  - name: "Adiciona Usuario Admin JBoss"
    shell: "/opt/liferay/jboss-eap-6.4/bin/add-user.sh liferay L1f3r4y!"
  - name: "Copia script jboss"
    copy:
     src: "/etc/ansible/arquivos/jboss_liferay/jboss"
     dest: "/etc/init.d/jboss"
     mode: 0755
  - name: "Cria usuario de serviço"
    user:
     name: liferay
  - name: correct java version selected
    alternatives:
     name: java
     path: /opt/java/bin/java
  - name: "Altera usuario diretorio LIFERAY"
    file: path=/opt/liferay owner=liferay group=liferay state=directory recurse=yes
  - name: "Remove arquivos .zip"
    shell: "cd /opt/; rm -rf *.zip"
