- hosts: all
  become: true
  become_user: root
  tasks:

##### VARIAVEIS #####
# - vars:
#    bumdle_liferay: liferay
#     java_version: jdk1.7.0_151
#     config_jboss: standalone.xml

##### SERVICOS #####
  - name: "Verifica Firewall UP/DOWN"
    service: name=firewalld state=stopped
  - name: "Desabilita Firewall"
    service: name=firewalld enabled=no
  - name: "Desabilita SELinux"
    selinux:
      state: disabled
  - name: "instalar java"
    yum: name=java state=latest

##### COPIAR PACOTES #####
  - name: "Copia pacote do Java para o diretorio de instalação"
    copy:
     src: "/etc/ansible/arquivos/jboss_liferay/{{ java_version }}.zip"
     dest: "/opt/{{ java_version }}.zip"
  - name: "Copia arquivos de Instalacao para /opt"
    copy:
     src: "/etc/ansible/arquivos/jboss_liferay/{{ bumdle_liferay }}.zip"
     dest: "/opt/{{ bumdle_liferay }}.zip"
  - name: "Descompactar Bumdle Liferay"
    shell: "cd /opt/; unzip {{ bumdle_liferay }}.zip"
  - name: "Configura standalone"
    copy:
     src: "/etc/ansible/arquivos/jboss_liferay/{{ config_jboss }}"
     dest: "/opt/liferay/jboss-eap-6.4/standalone/configuration/{{ config_jboss }}"
  - name: "Descompactar Java"
    shell: "cd /opt/; unzip {{ java_version }}.zip"

##### CONFIGURACOES #####
  - name: "Cria link simbolico"
    file:
     src: /opt/{{ java_version }}
     dest: /opt/java
     state: link
  - name: "Adiciona Usuario Admin JBoss"
    shell: "/opt/liferay/jboss-eap-6.4/bin/add-user.sh liferay L1f3r4y!"
  - name: "Copia script jboss"
    copy:
     src: "/etc/ansible/arquivos/jboss_liferay/jboss"
     dest: "/etc/init.d/jboss"
     mode: 0755
  - name: "Cria usuario de serviço"
    user:
     name: liferay
  - name: "Configurando Java via alternatives"
    alternatives:
     name: java
     path: /opt/java/bin/java
  - name: "Altera usuario diretorio LIFERAY"
    file: path=/opt/liferay owner=liferay group=liferay state=directory recurse=yes
  - name: "Remove arquivos .zip"
    shell: "cd /opt/; rm -rf *.zip"

