- hosts: all
  connection: paramiko
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: criar diretorio PID zabbix
      file:
        path: /var/run/zabbix
        state: directory
        mode: 0755
        owner: zabbix
      become: true

    - name: criar arquivo PID zabbix
      file:
        path: /var/run/zabbix/
        state: touch
        mode: 0755
        owner: zabbix
      become: true
    
    - name: reiniciar agente zabbix
      service:
        name: zabbix-agent
        state: restarted
      become: true
