- hosts: all
  connection: paramiko
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: reiniciar agente zabbix
      shell: "/etc/init.d/zabbix-agent restart"
      become: true
